dependencies:
  - name: graylog2-server
    version: 0.0.1
    repository: file://../graylog2-server
  - name: mongodb
    version: 0.4.18
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: elasticsearch
    version: 0.0.1
    repository: file://../elasticsearch
